### ISSUE TITLE
CSS on Admin section is not working

### ISSUE THREAD

**Issue by peloxoo** [MarcoCaballero/FFB_DAW#139]
@MarcoCaballero o @AdrianPedriza , la etiqueta body de bootstrap.min.css la cogen inherita absolutamente todas las demás hojas de estilo, y mi objetivo es poder modificar ciertos valores concretos dentro de algunas de mis páginas html, es decir, no quiero que la etiqueta body me "pise" los nuevos estilos que aplico.

**Comment by MarcoCaballero** [comment]
I find a way to resolve the issue.
If you change the <Body> background on <angular.cli.json> styles.css (Inherit import).
We could try to overwhelm the user background with .CSS

**Comment by peloxoo** [comment]
Thanks! I tried it and now it works!!
